spring:
  datasource:
    url: jdbc:mysql://localhost:3306/covid_dashboard?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    view:
      prefix: /
      suffix: .jsp
  messages.basename: validation
